# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yk66mek0yIvj8n4hcnTsfOC1AbahPCO0
"""

import os
import streamlit as st
import tensorflow as tf
import numpy as np

# ==================================================
# Page configuration
# ==================================================
st.set_page_config(
    page_title="Conditional VAE – MNIST Generator",
    page_icon="🧠",
    layout="centered"
)

# ==================================================
# Title
# ==================================================
st.title("🧠 Conditional VAE Digit Generator")
st.markdown(
    "This application generates MNIST digits using a "
    "**pre-trained Conditional Variational Autoencoder (CVAE)**."
)

# ==================================================
# Resolve model path (works locally and on Render)
# ==================================================
MODEL_PATH = os.path.join(os.getcwd(), "cvae_mnist_decoder.keras")

# ==================================================
# Load decoder model
# ==================================================
@st.cache_resource
def load_decoder():
    if not os.path.exists(MODEL_PATH):
        st.error(
            "Model file `cvae_mnist_decoder.keras` not found.\n\n"
            "Place it in the same directory as `app.py`."
        )
        st.stop()
    return tf.keras.models.load_model(MODEL_PATH)

decoder = load_decoder()

latent_dim = 2
num_classes = 10

# ==================================================
# User controls
# ==================================================
st.subheader("🎛 Generation Controls")

digit = st.selectbox("Select digit (0–9)", list(range(10)))
z1 = st.slider("Latent variable z₁", -3.0, 3.0, 0.0, 0.1)
z2 = st.slider("Latent variable z₂", -3.0, 3.0, 0.0, 0.1)

# ==================================================
# Generate image
# ==================================================
if st.button("🚀 Generate"):
    z = np.array([[z1, z2]], dtype=np.float32)
    label = tf.keras.utils.to_categorical([digit], num_classes)

    generated_image = decoder.predict([z, label], verbose=0)
    generated_image = generated_image.reshape(28, 28)

    st.subheader("🖼 Generated Digit")
    st.image(generated_image, width=250, clamp=True)


# ==================================================
# Footer
# ==================================================
st.markdown(
    """
    ---
    **Model:** Conditional Variational Autoencoder
    **Dataset:** MNIST
    **Framework:** TensorFlow · Streamlit
    """
)